staff_app/urls.py
from django.urls import path, include

from .views import (
    index,
    CompanyListView,
    ProfileDetailView,
    CompanyCreateView,
    CompanyDetailView,
    CompanyDeleteView,
    CompanyUpdateView,
    DepartmentCreateView,
    DepartmentUpdateView,
    DepartmentDetailView,
    DepartmentListView,
    PositionCreateView,
    PositionDetailView,
    PositionUpdateView,
    PositionListView,
    OfficeDetailView,
    OfficeCreateView,
    OfficeDeleteView,
    OfficeUpdateView,
    StaffUsernameUpdate,
    StaffNameSurnameUpdate,
    StaffEmailUpdateView,
    StaffLogoUpdateView,
    DepartmentDeleteView,
    PositionDeleteView,
    OfficeListView,
)

app_name = "staff_app"

clientarea_urlpatterns = [
    path("", CompanyListView.as_view(), name="clientarea"),
    path(
        "company-create/", CompanyCreateView.as_view(), name="company-create"
    ),
    path(
        "company-detail/<int:pk>/",
        CompanyDetailView.as_view(),
        name="company-detail",
    ),
    path(
        "company-detail/<int:pk>/offices/",
        OfficeListView.as_view(),
        name="office-list",
    ),
    path(
        "company-detail/<int:pk>/offices/create/",
        OfficeCreateView.as_view(),
        name="office-create",
    ),
    path(
        "company-detail/<int:pk>/offices/<int:office_id>/",
        OfficeDetailView.as_view(),
        name="office-detail",
    ),
    path(
        "company-detail/<int:pk>/offices/<int:office_id>/delete/",
        OfficeDeleteView.as_view(),
        name="office-delete",
    ),
    path(
        "company-detail/<int:pk>/offices/<int:office_id>/update/",
        OfficeUpdateView.as_view(),
        name="office-update",
    ),
    path(
        "company-detail/<int:pk>/departments/create",
        DepartmentCreateView.as_view(),
        name="department-create",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/delete",
        DepartmentDeleteView.as_view(),
        name="department-delete",
    ),
    path(
        "company-detail/<int:pk>/departments/",
        DepartmentListView.as_view(),
        name="department-list",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/",
        DepartmentDetailView.as_view(),
        name="department-detail",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/update/",
        DepartmentUpdateView.as_view(),
        name="department-update",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/<int:position_id>/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/<int:position_id>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/<int:position_id>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "company-detail/<int:pk>/delete/",
        CompanyDeleteView.as_view(),
        name="company-delete",
    ),
    path(
        "company-detail/<int:pk>/update/",
        CompanyUpdateView.as_view(),
        name="company-update",
    ),
    path("<int:pk>/", ProfileDetailView.as_view(), name="client-detail"),
    path(
        "<int:pk>/update-username/",
        StaffUsernameUpdate.as_view(),
        name="client-update-username",
    ),
    path(
        "<int:pk>/update-name-surname/",
        StaffNameSurnameUpdate.as_view(),
        name="client-update-name-surname",
    ),
    path(
        "<int:pk>/email-update/",
        StaffEmailUpdateView.as_view(),
        name="email-update",
    ),
    path(
        "<int:pk>/logo-update/",
        StaffLogoUpdateView.as_view(),
        name="logo-update",
    ),
]

urlpatterns = [
    path("", index, name="main-page"),
    path("clientarea/", include(clientarea_urlpatterns)),
]

staff_us_prjct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from staff_app.views import RegistrationView, login_test_user

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("staff_app.urls", namespace="staff_app")),
    path("login-test/", login_test_user, name="test-login"),
    path("accounts/register/", RegistrationView.as_view(), name="register"),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/includes/features.html
{% load static %}

<div class="fh5co-advantages-outer">
  <div class="container">
    <h1 class="second-title"><span class="span-perfect">>Efficient</span> <span class="span-features">Features</span></h1>
    <small>User-Friendly Interface</small>

    <div class="row fh5co-advantages-grid-columns wow animated fadeIn" data-wow-delay="0.36s">

      <div class="col-sm-4">
        <img class="grid-image" src="{% static 'img/icon-1.png' %}" alt="Icon-1">
        <h1 class="grid-title">Usability</h1>
        <p class="grid-desc">Simplify staff management with our intuitive and easy-to-use interface.</p>
      </div>

      <div class="col-sm-4">
        <img class="grid-image" src="{% static 'img/icon-2.png' %}" alt="Icon-2">
        <h1 class="grid-title">Seamless Collaboration</h1>
        <p class="grid-desc">Foster collaboration across company departments and offices effortlessly.</p>
      </div>

      <div class="col-sm-4">
        <img class="grid-image" src="{% static 'img/icon-3.png' %}" alt="Icon-3">
        <h1 class="grid-title">Customization Options</h1>
        <p class="grid-desc">Tailor your platform with a range of customization and branding choices.</p>
      </div>


    </div>
  </div>
</div>

templates/includes/footer.html
{% load static %}

<footer class="footer-outer">
  <div class="container footer-inner">

    <div class="footer-three-grid wow fadeIn animated" data-wow-delay="0.66s">
      <div class="column-1-3">
        <h1>App</h1>
      </div>
      <div class="column-2-3">
        <nav class="footer-nav">
          <ul>
            <a href="#" onclick="$('#fh5co-hero-wrapper').goTo();return false;"><li>Home</li></a>
            <a href="#" onclick="$('#fh5co-features').goTo();return false;"><li>Features</li></a>
            <a href="#" onclick="$('#fh5co-reviews').goTo();return false;"><li>Reviews</li></a>
          </ul>
        </nav>
      </div>
    </div>

    <span class="border-bottom-footer"></span>

    <p class="copyright">&copy; 2018 App. All rights reserved. Design by <a href="https://freehtml5.co" target="_blank">FreeHTML5</a>.</p>

  </div>
</footer>

templates/includes/header.html
{% load static %}
<body>
<nav class="style-1">
  <a href="{% url 'staff_app:clientarea' %}" class="btn">Companies</a>
  <a href="{% url 'staff_app:client-detail' request.user.pk %}" class="btn">Profile</a>
  <a href="{% url 'logout' %}?next=/" class="btn">Log out</a>
</nav>

templates/includes/hero.html
{% load static %}

<div id="fh5co-hero-wrapper">
  <nav class="container navbar navbar-expand-lg main-navbar-nav navbar-light">
    <a class="navbar-brand" href="">StaffUs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav nav-items-center ml-auto mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" onclick="$('#fh5co-features').goTo();return false;">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#reviews" onclick="$('#fh5co-reviews').goTo();return false;">Reviews</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-primary special-login-button" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-primary special-login-button" href="{% url 'register' %}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-primary special-login-button" href="{% url 'test-login' %}">Test User</a>
        </li>
      </ul>
    </div>

  </nav>

  <div class="container fh5co-hero-inner">
    <h1 class="animated fadeIn wow" data-wow-delay="0.4s">Streamline Your Staff Management with Our Platform</h1>
    <p class="animated fadeIn wow" data-wow-delay="0.67s">Effortlessly organize your company's departments and offices for improved efficiency and collaboration. </p>
    <button class="btn btn-md download-btn-first wow fadeInLeft animated" data-wow-delay="0.85s"><a class="btn" href="{% url 'register' %}">Sign Up</a></button>
    <button class="btn btn-md features-btn-first animated fadeInLeft wow" data-wow-delay="0.95s" onclick="$('#fh5co-features').goTo();return false;">Features</button>
    <img class="fh5co-hero-smartphone animated fadeInRight wow" data-wow-delay="1s" src="{% static 'img/company-organization-hierarchy-schema-template-vector-22656285(1).webp' %}" alt="Smartphone">
  </div>


</div> <!-- first section wrapper -->

templates/includes/paginator.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
      </li>
    {% endif %}
    <li class="page-item">
      <select class="page-link" onchange="window.location.href = this.value;">
        {% for page_num in paginator.page_range %}
          <option value="?page={{ page_num }}" {% if page_num == page_obj.number %}selected{% endif %}>
            Page {{ page_num }}
          </option>
        {% endfor %}
      </select>
    </li>
  </ul>
{% endif %}

templates/includes/reviews.html
{% load static %}

<div id="fh5co-reviews" class="fh5co-reviews-outer">
  <h1>What people are saying</h1>
  <small>Reviews</small>
  <div class="container fh5co-reviews-inner">
    <div class="row justify-content-center">
      <div class="col-sm-5 wow fadeIn animated" data-wow-delay="0.25s">
        <img class="float-left" src="{% static 'img/quotes-1.jpg' %}" alt="Quote 1">
        <p class="testimonial-desc">Our platform has transformed the way we manage staff and company departments.</p>
        <small class="testimonial-author">Owner</small>
        <img class="float-right" src="{% static 'img/quotes-2.jpg' %}" alt="Quote 2">
      </div>
      <div class="col-sm-5 testimonial-2 wow fadeIn animated" data-wow-delay="0.67s">
        <img class="float-left" src="{% static 'img/quotes-1.jpg' %}" alt="Quote 1">
        <p class="testimonial-desc">I can't believe how seamless collaboration has become with this platform.</p>
        <small class="testimonial-author">Someone</small>
        <img class="float-right" src="{% static 'img/quotes-2.jpg' %}" alt="Quote 2">
      </div>
    </div>

  </div>
</div>

templates/includes/scripts.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/includes/slider.html
{% load static %}

<div class="fh5co-slider-outer wow fadeIn" data-wow-delay="0.36s">
  <h1>SIMPLE WIDGETS</h1>
  <small>Drag and Drop</small>
  <div class="container fh5co-slider-inner">

    <div class="owl-carousel owl-theme">

      <div class="item"><img src="{% static 'img/organization-schema-markup.webp' %}" alt=""></div>
      <div class="item"><img src="{% static 'img/department.png' %}" alt=""></div>
      <div class="item"><img src="{% static 'img/office.png' %}" alt=""></div>


    </div>

  </div>
</div>