staff_app/urls.py
from django.urls import path, include

from .views import (
    index,
    CompanyListView,
    ProfileDetailView,
    CompanyCreateView,
    CompanyDetailView,
    CompanyDeleteView,
    CompanyUpdateView,
    DepartmentCreateView,
    DepartmentUpdateView,
    DepartmentDetailView,
    DepartmentListView,
    PositionCreateView,
    PositionDetailView,
    PositionUpdateView,
    PositionListView,
    OfficeDetailView,
    OfficeCreateView,
    OfficeDeleteView,
    OfficeUpdateView,
    StaffUsernameUpdate,
    StaffNameSurnameUpdate,
    StaffEmailUpdateView,
    StaffLogoUpdateView,
    DepartmentDeleteView,
    PositionDeleteView,
    OfficeListView,
)

app_name = "staff_app"

clientarea_urlpatterns = [
    path("", CompanyListView.as_view(), name="clientarea"),
    path(
        "company-create/", CompanyCreateView.as_view(), name="company-create"
    ),
    path(
        "company-detail/<int:pk>/",
        CompanyDetailView.as_view(),
        name="company-detail",
    ),
    path(
        "company-detail/<int:pk>/offices/",
        OfficeListView.as_view(),
        name="office-list",
    ),
    path(
        "company-detail/<int:pk>/offices/create/",
        OfficeCreateView.as_view(),
        name="office-create",
    ),
    path(
        "company-detail/<int:pk>/offices/<int:office_id>/",
        OfficeDetailView.as_view(),
        name="office-detail",
    ),
    path(
        "company-detail/<int:pk>/offices/<int:office_id>/delete/",
        OfficeDeleteView.as_view(),
        name="office-delete",
    ),
    path(
        "company-detail/<int:pk>/offices/<int:office_id>/update/",
        OfficeUpdateView.as_view(),
        name="office-update",
    ),
    path(
        "company-detail/<int:pk>/departments/create",
        DepartmentCreateView.as_view(),
        name="department-create",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/delete",
        DepartmentDeleteView.as_view(),
        name="department-delete",
    ),
    path(
        "company-detail/<int:pk>/departments/",
        DepartmentListView.as_view(),
        name="department-list",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/",
        DepartmentDetailView.as_view(),
        name="department-detail",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/update/",
        DepartmentUpdateView.as_view(),
        name="department-update",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/<int:position_id>/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/<int:position_id>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/<int:position_id>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "company-detail/<int:pk>/departments/<int:id>/positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "company-detail/<int:pk>/delete/",
        CompanyDeleteView.as_view(),
        name="company-delete",
    ),
    path(
        "company-detail/<int:pk>/update/",
        CompanyUpdateView.as_view(),
        name="company-update",
    ),
    path("<int:pk>/", ProfileDetailView.as_view(), name="client-detail"),
    path(
        "<int:pk>/update-username/",
        StaffUsernameUpdate.as_view(),
        name="client-update-username",
    ),
    path(
        "<int:pk>/update-name-surname/",
        StaffNameSurnameUpdate.as_view(),
        name="client-update-name-surname",
    ),
    path(
        "<int:pk>/email-update/",
        StaffEmailUpdateView.as_view(),
        name="email-update",
    ),
    path(
        "<int:pk>/logo-update/",
        StaffLogoUpdateView.as_view(),
        name="logo-update",
    ),
]

urlpatterns = [
    path("", index, name="main-page"),
    path("clientarea/", include(clientarea_urlpatterns)),
]

staff_us_prjct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from staff_app.views import RegistrationView, login_test_user

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("staff_app.urls", namespace="staff_app")),
    path("login-test/", login_test_user, name="test-login"),
    path("accounts/register/", RegistrationView.as_view(), name="register"),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

staff_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model  # Import get_user_model

from .models import Company, Department, StaffUser


class RegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "password1", "password2")


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = (
            "name",
            "foundation_date",
            "copmany_staff_size",
            "description",
            "country_registry",
            "logo",
        )


class StaffUsernameUpdateForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class StaffNameSurnameUpdateForm(ModelForm):
    class Meta:
        model = StaffUser
        fields = ("first_name", "last_name")


class StaffEmailUpdateForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("email",)


class StaffLogoUpdateForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("logo",)


class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = ("name", "description")

staff_app/views.py
import datetime

from django.contrib.auth import login, authenticate
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpRequest
from django.views.generic import (
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
    ListView,
)
from django.views.generic.list import MultipleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from staff_app.models import (
    StaffUser,
    Company,
    Department,
    Position,
    Office,
)

from staff_app.forms import (
    RegistrationForm,
    CompanyForm,
    DepartmentForm,
    StaffUsernameUpdateForm,
    StaffNameSurnameUpdateForm,
    StaffEmailUpdateForm,
    StaffLogoUpdateForm,
)


def index(request: HttpRequest):
    return render(request, "staff_app/index.html")


def login_test_user(request):
    user = authenticate(request, username="user36", password="GGduIU@")
    login(request, user)
    return redirect("staff_app:clientarea")


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = StaffUser
    context_object_name = "staffuser"
    template_name = "staff_app/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_companies"] = (
            Company.objects.select_related("owner")
            .filter(owner__id=self.request.user.pk)
            .order_by("-created_at_staff")[:5]
        )
        return context


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = "staff_app/compnay-creation.html"
    success_url = reverse_lazy("staff_app:clientarea")

    def form_valid(self, form):
        form.instance.owner_id = self.request.user.id
        return super().form_valid(form)


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = "staff_app/company-update.html"

    def get_success_url(self):
        return self.object.get_absolute_url()


class CompanyDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Company
    template_name = "staff_app/company-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            object_list=self.object.departments.all(), **kwargs
        )
        context["offices_count"] = self.object.company_offices.count()
        context["departments"] = self.object.departments.all()[:5]
        context["total_departments"] = self.object.departments.count()
        return context


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    success_url = reverse_lazy("staff_app:clientarea")


class CompanyListView(LoginRequiredMixin, ListView):
    model = Company
    template_name = "staff_app/clientarea.html"
    context_object_name = "companies_list"
    paginate_by = 3

    def get_queryset(self):
        return Company.objects.prefetch_related(
            "company_offices", "departments"
        ).filter(owner=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        companies = self.get_queryset()
        context["departments_count"] = {
            company.pk: company.departments.count() for company in companies
        }
        context["offices_count"] = {
            company.pk: company.company_offices.count()
            for company in companies
        }
        context["company_exists"] = {
            company.pk: (datetime.date.today() - company.created_at_staff).days
            + 1
            for company in companies
        }
        context["total_companies"] = companies.count()
        return context


class DepartmentCreateView(LoginRequiredMixin, CreateView):
    model = Department
    form_class = DepartmentForm

    def form_valid(self, form):
        form.instance.company = Company.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)


class DepartmentDeleteView(LoginRequiredMixin, DeleteView):
    model = Department

    def get_object(self):
        return get_object_or_404(
            Department, pk=self.kwargs["id"], company_id=self.kwargs["pk"]
        )

    def get_success_url(self):
        return reverse_lazy(
            "staff_app:department-list",
            kwargs={"pk": self.kwargs["pk"]},
        )


class DepartmentUpdateView(LoginRequiredMixin, UpdateView):
    model = Department
    form_class = DepartmentForm

    def get_object(self):
        return get_object_or_404(
            Department, pk=self.kwargs["id"], company_id=self.kwargs["pk"]
        )

    def get_success_url(self):
        return self.object.get_absolute_url()


class DepartmentDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Department
    context_object_name = "department"

    def get_object(self):
        return get_object_or_404(
            Department, pk=self.kwargs["id"], company_id=self.kwargs["pk"]
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            object_list=self.object.positions.all(), **kwargs
        )
        context["positions_count"] = self.object.positions.count()
        context["positions"] = self.object.positions.all()[:5]
        return context

    def get_success_url(self):
        return self.object.get_absolute_url()


class DepartmentListView(LoginRequiredMixin, ListView):
    model = Department
    paginate_by = 3

    def get_queryset(self):
        return self.model.objects.select_related("company").filter(
            company__pk=self.kwargs["pk"]
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["company"] = Company.objects.get(pk=self.kwargs["pk"])
        context["total_departments"] = context["company"].departments.count()
        return context


class PositionCreateView(LoginRequiredMixin, CreateView):
    model = Position
    fields = ("name", "description")

    def form_valid(self, form):
        form.instance.department = Company.objects.get(
            pk=self.kwargs["pk"]
        ).departments.get(pk=self.kwargs["id"])

        return super().form_valid(form)

    def get_success_url(self):
        return self.object.get_absolute_url()


class PositionDetailView(LoginRequiredMixin, DetailView):
    model = Position

    def get_object(self):
        return get_object_or_404(
            Position,
            pk=self.kwargs["position_id"],
        )

    def get_success_url(self):
        return self.object.get_absolute_url()


class PositionListView(LoginRequiredMixin, ListView):
    model = Position
    paginate_by = 3

    def get_queryset(self):
        return self.model.objects.select_related("department").filter(
            department_id=self.kwargs["id"]
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["department"] = (
            Department.objects.select_related(
                "company",
            )
            .prefetch_related("positions")
            .get(pk=self.kwargs["id"])
        )
        context["department_total_positions"] = context[
            "department"
        ].positions.count()
        return context


class PositionUpdateView(LoginRequiredMixin, UpdateView):
    model = Position
    fields = ("name", "description")

    def get_object(self):
        return get_object_or_404(
            Position,
            pk=self.kwargs["position_id"],
        )

    def get_success_url(self):
        return self.object.get_absolute_url()


class PositionDeleteView(LoginRequiredMixin, DeleteView):
    model = Position

    def get_object(self):
        return get_object_or_404(
            Position,
            pk=self.kwargs["position_id"],
        )

    def get_success_url(self):
        return self.object.department.get_absolute_url()


class OfficeCreateView(LoginRequiredMixin, CreateView):
    model = Office
    fields = [
        "name",
        "city",
        "country",
        "address",
        "workspaces",
        "description",
    ]

    def form_valid(self, form):
        form.instance.company = Company.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "staff_app:office-detail",
            kwargs={"pk": self.kwargs["pk"], "office_id": self.object.pk},
        )


class OfficeUpdateView(LoginRequiredMixin, UpdateView):
    model = Office
    fields = [
        "name",
        "city",
        "country",
        "address",
        "workspaces",
        "description",
        "company",
    ]
    success_url = reverse_lazy("staff_app:clientarea")

    def get_object(self):
        return get_object_or_404(
            self.model, pk=self.kwargs["office_id"], company=self.kwargs["pk"]
        )

    def get_success_url(self):
        return reverse_lazy(
            "staff_app:office-detail",
            kwargs={"pk": self.kwargs["pk"], "office_id": self.object.pk},
        )


class OfficeDetailView(LoginRequiredMixin, DetailView):
    model = Office

    def get_object(self):
        return get_object_or_404(
            self.model, pk=self.kwargs["office_id"], company=self.kwargs["pk"]
        )


class OfficeListView(LoginRequiredMixin, ListView):
    model = Office
    paginate_by = 3

    def get_queryset(self):
        return self.model.objects.filter(company__pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["company"] = Company.objects.get(pk=self.kwargs["pk"])
        context["total_offices"] = context["company"].company_offices.count()
        return context


class OfficeDeleteView(LoginRequiredMixin, DeleteView):
    model = Office

templates/staff_app/company-detail.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profile Page</title>
  <link rel="stylesheet" href="{% static 'css/header.css' %}">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>

{% block header %}
  {% include 'includes/header.html' %}
{% endblock %}

<body>
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">

          <img class="rounded-circle mt-5" width="150px" {% if company.logo %} src="{{ company.logo.url }}" {% else %} src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" alt="{{ company.name }} Logo" {% endif %}>
        <span class="font-weight-bold">
          <a href="{% url 'staff_app:company-update' company.pk %}" class="btn btn-primary">Update</a>
          <span><a href="{% url 'staff_app:company-delete' company.pk %}" class="btn btn-danger">Delete</a></span>
        </span>
        <span class="text-black-50">{{ staffuser.email }}</span>
        <span> </span>
      </div>
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="text-right">{{ company.name }}</h4>
        </div>
        <div class="row mt-2">
          <div class="col-md-6"><label class="labels">Created</label><span class="form-control">{{ company.created_at_staff }}</span></div>
          <div class="col-md-6"><label class="labels">Staff size</label><span class="form-control">{{ company.copmany_staff_size }}</span></div>
        </div>
        <div class="row mt-3">
          <div class="col-md-12"><label class="labels">Description</label><span class="form-control">{{ company.description }}</span></div>
          <div class="col-md-12"><label class="labels">Country</label><span class="form-control">{{ company.country_registry }}</span></div>
        </div>
        <div class="row mt-3">
          <div class="col-md-6"><label class="labels">Foundation date</label><span class="form-control">{{ company.foundation_date }}</span></div>
          <div class="col-md-6"><label class="labels">Offices amount</label><span class="form-control">{{ offices_count }}</span></div>
        </div>
        <div class="mt-5 text-center">
          <button class="btn btn-primary profile-button" type="button" onclick="window.location.href='{% url 'staff_app:clientarea' %}'">Back to companies</button>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="p-3 py-5">

        {% if departments %}
          <div class="col-md-12"><label class="labels">Departments list (total: {{ total_departments }}):</label></div>
          <div class="col-md-12"><label class="labels"></label></div>
          {% for department in departments %}
            <div class="col-md-12"><span class="form-control"><a href="{% url 'staff_app:department-detail' id=department.pk pk=company.pk %}">{{ department.name }}</a></span></div><br>
          {% endfor %}
        {% else %}
          <div><h5>No departments yet</h5> <a href="{% url 'staff_app:department-create' pk=company.pk %}" class="text-right">Create department</a></div>
        {% endif %}
        {% block pagination %}
        <div class="text-center">
          {% include "includes/paginator.html" %}
        </div>
        {% endblock %}
        <div><a href="{% url 'staff_app:department-create' pk=company.pk %}" class="btn btn-primary">Create department</a> <a href="{% url 'staff_app:department-list' pk=company.pk %}" class="text-center">See all</a></div>
        <br>
        <div><a href="{% url 'staff_app:office-create' pk=company.pk %}" class="btn btn-primary">Create office</a>  <a href="{% url 'staff_app:office-list' pk=company.pk %}" class="text-right">See offices</a></div>

      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</body>

templates/staff_app/department_confirm_delete.html
{% extends 'staff_app/department_detail.html' %}

{% block delete %}
<div class="col-md-4">
  <div class="text-center" ><h5>Are you sure that you want to delete this department? All information about it will be deleted.</h5></div>
  <form action="" method="post">
    {% csrf_token %}
    <div class="mt-5 text-center"><input type="submit" value="Yes" class="btn btn-danger"></div>
    <div class="mt-5 text-center">
      <button class="btn btn-primary profile-button" type="button" onclick="goBack()">Back</button>

      <script>
          function goBack() {
              window.history.back();
          }
      </script>
    </div>
  </form>
</div>
{% endblock %}

templates/staff_app/index.html
{% extends 'base.html' %}

{% block content %}

<body>


<div id="page-wrap">


{% block hero %}
	{% include 'includes/hero.html' %}
{% endblock %}

{% block features %}
  {% include 'includes/features.html' %}
{% endblock %}


{% block slider %}
	{% include 'includes/slider.html' %}
{% endblock %}

{% block reviews %}
	{% include 'includes/reviews.html' %}
{% endblock %}

  <!-- ==========================================================================================================
                                             SECTION 7 - SUB FOOTER
  ========================================================================================================== -->

  {% block footer %}
  	{% include 'includes/footer.html' %}
  {% endblock %}

</div> <!-- main page wrapper -->

{% block scripts %}
	{% include 'includes/scripts.html' %}
{% endblock %}
</body>
</html>
{% endblock %}

templates/staff_app/office_detail.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profile Page</title>
  <link rel="stylesheet" href="{% static 'css/header.css' %}">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>

{% block header %}
{% include 'includes/header.html' %}
{% endblock %}

<body>
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">

        <img class="rounded-circle mt-5" width="150px" src="https://media.istockphoto.com/id/1460755337/photo/white-color-theme-modern-style-office-with-exposed-concrete-floor-and-a-lot-of-plant-3d.webp?b=1&s=170667a&w=0&k=20&c=vjO4QhU7YP-UEdHsrECZH01Nvj0T5aqnoWSh02XdLeo=" alt="{{ office.name }} Logo">
        <span class="font-weight-bold">
          <a href="{% url 'staff_app:office-update' pk=object.company.pk office_id=object.pk %}" class="btn btn-primary">Update</a>
          <span><a href="{% url 'staff_app:office-delete' pk=object.company.pk office_id=object.pk %}" class="btn btn-danger">Delete</a></span>
        </span>
        <span> </span>
      </div>
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="text-right">{{ object.name }}</h4>
        </div>
        <div class="row mt-2">
          <div class="col-md-6"><label class="labels">Created</label><span class="form-control">{% if object.opened %} {{ object.opened }} {% else %} No data {% endif %}</span></div>
          <div class="col-md-6"><label class="labels">Belongs to</label><span class="form-control"><a
              href="{% url 'staff_app:company-detail' pk=object.company.pk %}">{{ object.company.name }}</a></span></div>
        </div>
        <div class="row mt-3">
          <div class="col-md-12"><label class="labels">Description</label><span class="form-control">{{ object.description }}</span></div>
        </div>
        <div class="row mt-2">
          <div class="col-md-6"><label class="labels">Country</label><span class="form-control">{{ object.country }}</span></div>
          <div class="col-md-6"><label class="labels">City</label><span class="form-control">{{ object.city }}</span></div>
        </div>
        <div class="row mt-3">
          <div class="col-md-12"><label class="labels">Address</label><span class="form-control">{{ object.address }}</span></div>
        </div>
        <div class="mt-5 text-center">
          <button class="btn btn-primary profile-button" type="button" onclick="window.location.href='{% url 'staff_app:clientarea' %}'">Back to companies</button>
        </div>
      </div>
    </div>
    {% block delete %}
    <div class="col-md-4">
      <div class="p-3 py-5">
        <div><a href="" class="btn btn-primary">Create new object for this department</a> <a href="" class="text-center">See all</a></div>
      </div>
    </div>
    {% endblock %}
  </div>
</div>
</div>
</div>
</div>
</body>

templates/staff_app/position_detail.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profile Page</title>
  <link rel="stylesheet" href="{% static 'css/header.css' %}">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>

{% block header %}
  {% include 'includes/header.html' %}
{% endblock %}

<body>
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">

        <img class="rounded-circle mt-5" width="150px" src="https://images.pexels.com/photos/5602166/pexels-photo-5602166.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="{{ department.name }} Logo">
        <span class="font-weight-bold">
          <a href="{% url 'staff_app:position-update' id=object.department.pk pk=object.department.company.pk position_id=object.pk %}" class="btn btn-primary">Update</a>
          <span><a href="{% url 'staff_app:position-delete' pk=object.department.company.pk id=object.department.pk position_id=object.pk %}" class="btn btn-danger">Delete</a></span>
        </span>
        <span> </span>
      </div>
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="text-right">{{ object.name }}</h4>
        </div>
        <div class="row mt-2">
          <div class="col-md-6"><label class="labels">Created</label><span class="form-control">{{ object.created_at_staff }}</span></div>
          <div class="col-md-6"><label class="labels">Belongs to department</label><span class="form-control"><a
              href="{% url 'staff_app:department-detail' pk=object.department.company.pk id=object.department.pk %}">{{ object.department.name }}</a></span></div>
        </div>
        <div class="row mt-3">
          <div class="col-md-12"><label class="labels">Description</label><span class="form-control">{{ object.description }}</span></div>
        </div>
        <div class="row mt-3">
        </div>
        <div class="mt-5 text-center">
          <button class="btn btn-primary profile-button" type="button" onclick="window.location.href='{% url 'staff_app:clientarea' %}'">Back to companies</button>
        </div>
      </div>
    </div>
    {% block delete %}
    <div class="col-md-4">
      <div class="p-3 py-5">
        <a href="{% url 'staff_app:position-create' id=position.department.pk pk=position.department.company.pk %}"
             class="btn btn-primary">Create another position</a>
          <a href="{% url 'staff_app:position-list' id=position.department.pk pk=position.department.company.pk %}" class="text-center">See all</a></div>
      </div>
    </div>
    {% endblock %}
  </div>
</div>
</div>
</div>
</div>
</body>